--#lab9
--#1
DECLARE @var1 char='a', 
		@var2 varchar='qweqwe',
		@var3 datetime,
		@var4 time,
		@var5 int,
		@var6 smallint,
		@var7 tinyint,
		@var8 numeric(13,5);

SET @var3=GETDATE();
SET @var4=SYSDATETIME();
SELECT	@var5=777,
		@var6 =543;
SET @var7 = 234;
SET @var8 = 12345342.12345;
PRINT 'VARIABLES 1-4: '+ @var1 + ' '+ @var2 + ' '+ CONVERT(varchar,@var3) +' '+CONVERT(varchar,@var4) ;
SELECT @var5[var5],@var6[var6],@var7 as var7,@var8 var8
--#2
DECLARE @X1 INT = (SELECT SUM(AUDITORIUM_CAPACITY) FROM AUDITORIUM),@X2 SMALLINT,@X3 REAL, @X4 SMALLINT, @X5 REAL
PRINT 'îáùàÿ âìåñòèìîñòü: '+CAST(@X1 AS CHAR)
IF @X1>200
	BEGIN
		SET @X2 = (SELECT COUNT(*) FROM AUDITORIUM);
		SET @X3 = (SELECT Avg(CAST(AUDITORIUM_CAPACITY AS numeric(10,2))) FROM AUDITORIUM);
		SET @X4 = (SELECT COUNT(*) FROM AUDITORIUM WHERE AUDITORIUM_CAPACITY<@X3);
		SET @X5 = CONVERT(REAL,@X4)/CONVERT(REAL,@X2)*100;
		SELECT @X1[ÎÁÙÀß ÂÌÅÑÒÈÌÎÑÒÜ],@X2[ÊÎËÈ×ÅÑÒÂÎ ÀÓÄÈÒÎÐÈÉ],@X3[AVG],@X4[CAPACITY<AVG],@X5[%]
	END
ELSE
	PRINT 'îáùàÿ âìåñòèìîñòü: '+CAST(@X1 AS CHAR);
--#3
SELECT	@@ROWCOUNT[PROCESSED_STR],@@VERSION[VERSION],@@SPID[ID],@@ERROR[LAST_ERROR],@@SERVERNAME[SERVER_NAME],
		@@TRANCOUNT[NESTING_LEVEL_OF_TRAN],@@FETCH_STATUS[CHECK_RESULT],@@NESTLEVEL[NESTING_LEVELE_OF_PROC]
--#4
	--#4.1
		DECLARE @T REAL,@X REAL,@Z REAL
		SET @T =2.3;
		SET @X = 1;
		IF @T>@X
			BEGIN
				SET @Z=POWER(SIN(@T),2);
				PRINT 'Z: ' + CONVERT(NVARCHAR,@Z);
			END
		ELSE IF @T<@X
			BEGIN
				SET @Z=4*(@T+@X);
				PRINT 'Z: ' + CONVERT(NVARCHAR,@Z);
			END
		ELSE
			BEGIN
				SET @Z=1-EXP(@X-2);
				PRINT 'Z: ' + CONVERT(NVARCHAR,@Z);
			END
	--#4.2
		DECLARE @FIO NVARCHAR(50) = 'SMOLIK VALERIY ALEKSANDROVICH';
		SET @FIO = REPLACE(@FIO,' ','.');
		DECLARE @SURNAME NVARCHAR(20) = PARSENAME(@FIO,3);
		DECLARE @NAME NVARCHAR(20) = PARSENAME(@FIO,2);
		DECLARE @PATRONYMIC NVARCHAR(20) = PARSENAME(@FIO,1);
		PRINT 'TO SURNAME.N.P: '+@SURNAME +' '+SUBSTRING(@NAME,1,1)+'.'+SUBSTRING(@PATRONYMIC,1,1);
	--#4.3 
		DECLARE @CURRENTDATE DATETIME = GETDATE();
		SET @CURRENTDATE = DATEADD(MONTH,1,@CURRENTDATE);
		SELECT NAME, STUDENT.BDAY, DATEDIFF(YEAR, STUDENT.BDAY, SYSDATETIME()) AS ÂÎÇÐÀÑÒ
			FROM STUDENT 
				WHERE DATEPART(MONTH,@CURRENTDATE) IN (DATEPART(MONTH,STUDENT.BDAY));
	--#4.4 
	DECLARE @DAY1 nvarchar =(SELECT DATENAME(DAY,PDATE) FROM PROGRESS 
						WHERE SUBJECT LIKE'ÑÓÁÄ'
						GROUP BY PDATE) 
	SELECT @DAY1[DAY_OF_WEEK];
--#5
DECLARE @NUMBEROFSTUD INT =(SELECT COUNT(*)FROM PROGRESS)
DECLARE @AVGMARK REAL = (SELECT Avg(CAST(NOTE AS numeric(10,2))) FROM PROGRESS)
IF(@AVGMARK>5 AND @AVGMARK<6)
	PRINT'AVG HIGHER THEN 5 AND SMALLER THEN 6:'+CONVERT(NVARCHAR,@AVGMARK)+' NUMBER OF STUDENT :'+CAST(@NUMBEROFSTUD AS NVARCHAR)
ELSE IF(@AVGMARK<5)
	PRINT 'AVG SMALLER THEN 5:'+CONVERT(NVARCHAR,@AVGMARK)+' NUMBER OF STUDENT :'+CAST(@NUMBEROFSTUD AS NVARCHAR)
ELSE 
	PRINT 'AVG HIGHER THEN 6:'+CONVERT(NVARCHAR(10),@AVGMARK)+' NUMBER OF STUDENT :'+CAST(@NUMBEROFSTUD AS NVARCHAR)
--#6
SELECT 
CASE
	WHEN NOTE = 7 THEN 'MARK 7'
	WHEN NOTE = 8 THEN 'MARK 8'
	WHEN NOTE = 9 THEN 'MARK 9'
	WHEN NOTE = 10 THEN 'MARK 10'
	ELSE 'OTHER MARK'
END[MARKS],COUNT(*)[COUNT]
FROM PROGRESS
GROUP BY
CASE
	WHEN NOTE = 7 THEN 'MARK 7'
	WHEN NOTE = 8 THEN 'MARK 8'
	WHEN NOTE = 9 THEN 'MARK 9'
	WHEN NOTE = 10 THEN 'MARK 10'
	ELSE 'OTHER MARK'
END

--#7
CREATE TABLE #TEMPORARY
	(	
		COLUMN1 INT,
		COLUMN2 VARCHAR(10),
		COLUMN3 REAL
	);

DECLARE @COUNTER INT =0;
WHILE (@COUNTER<10)
BEGIN
	INSERT #TEMPORARY
		VALUES(FLOOR(10*RAND()),'ASDASD',9.23123*RAND())
	IF (@COUNTER % 10=0)
		PRINT @COUNTER;
	SET @COUNTER +=1
END

SELECT *FROM #TEMPORARY
DROP TABLE #TEMPORARY

--#8
DECLARE @Y1 INT =1
PRINT @Y1+1
PRINT @Y1+2
RETURN
PRINT @Y1+3
--#9
USE TEST
BEGIN TRY
	UPDATE TESTING
		SET VAR2 = 10
		WHERE VAR1 = 4
END TRY
BEGIN CATCH
	PRINT ERROR_NUMBER()
	PRINT ERROR_MESSAGE()
	PRINT ERROR_LINE()
	PRINT ERROR_PROCEDURE()
	PRINT ERROR_SEVERITY()
	PRINT ERROR_STATE()
END CATCH

