USE UNIVER--lab5
	--#1
		SELECT PULPIT.PULPIT_NAME,FACULTY.FACULTY_NAME,PROFESSION.PROFESSION_NAME
			FROM PULPIT,FACULTY,PROFESSION
				WHERE	PULPIT.FACULTY =FACULTY.FACULTY
									AND
						FACULTY.FACULTY=PROFESSION.FACULTY
									AND
						FACULTY.FACULTY_NAME IN (SELECT FACULTY_NAME
												FROM FACULTY
												WHERE (FACULTY_NAME LIKE '%технология%' )OR 
														(FACULTY_NAME LIKE '%технологии%'))
	--#2
	SELECT PULPIT.PULPIT_NAME,FACULTY.FACULTY_NAME,PROFESSION.PROFESSION_NAME
			FROM PULPIT
			INNER JOIN FACULTY
				ON FACULTY.FACULTY = PULPIT.FACULTY
			INNER JOIN PROFESSION
				ON PROFESSION.FACULTY=FACULTY.FACULTY
				WHERE FACULTY.FACULTY_NAME IN (SELECT FACULTY_NAME
												FROM FACULTY
												WHERE (FACULTY_NAME LIKE '%технология%' )OR 
														(FACULTY_NAME LIKE '%технологии%'))
	--#3
		SELECT PULPIT.PULPIT_NAME,FACULTY.FACULTY_NAME,PROFESSION.PROFESSION_NAME
			FROM PULPIT
			INNER JOIN FACULTY
				ON FACULTY.FACULTY=PULPIT.FACULTY
			INNER JOIN PROFESSION
				ON PROFESSION.FACULTY = FACULTY.FACULTY
				WHERE	(FACULTY_NAME LIKE '%технология%' )	OR 
						(FACULTY_NAME LIKE '%технологии%')

	--#4
		SELECT a.AUDITORIUM_CAPACITY,a.AUDITORIUM_TYPE
			FROM AUDITORIUM a 
				WHERE AUDITORIUM_CAPACITY=(SELECT TOP(1) AUDITORIUM_CAPACITY FROM AUDITORIUM aa
											WHERE A.AUDITORIUM_TYPE=AA.AUDITORIUM_TYPE
											ORDER BY AUDITORIUM_CAPACITY DESC)

	--#5
	SELECT FACULTY.FACULTY_NAME,FACULTY.FACULTY
		FROM FACULTY
			WHERE NOT EXISTS(SELECT PULPIT.FACULTY FROM PULPIT
								WHERE FACULTY.FACULTY=PULPIT.FACULTY)
	--#6
	SELECT TOP 1
		(SELECT AVG(NOTE)FROM PROGRESS WHERE SUBJECT LIKE 'ОАиП')[ОАиП],
		(SELECT AVG(NOTE)FROM PROGRESS WHERE SUBJECT LIKE 'БД ')[БД],
		(SELECT AVG(NOTE)FROM PROGRESS WHERE SUBJECT LIKE 'СУБД ')[СУБД]
	FROM PROGRESS
	--#7
	SELECT PROGRESS.SUBJECT,PROGRESS.NOTE,PROGRESS.PDATE
		FROM PROGRESS
			WHERE PROGRESS.NOTE<=ALL(SELECT PROGRESS.NOTE FROM PROGRESS
										WHERE PROGRESS.SUBJECT LIKE'с%')
	--#8
	SELECT PROGRESS.SUBJECT,PROGRESS.NOTE,PROGRESS.PDATE
		FROM PROGRESS
			WHERE PROGRESS.NOTE>=ANY(SELECT PROGRESS.NOTE FROM PROGRESS
										WHERE PROGRESS.SUBJECT LIKE'с%')

	--#9 DOP
	SELECT STUDENT.NAME,BDAY
	FROM STUDENT
	WHERE STUDENT.BDAY IN(
	SELECT STUDENT.BDAY
	FROM STUDENT
		GROUP BY STUDENT.BDAY
			HAVING COUNT(STUDENT.BDAY)>1)
		
	
			