--lab7
--#1
	SELECT PROGRESS.SUBJECT,GROUPS.PROFESSION,
	ROUND(AVG(CAST(PROGRESS.NOTE AS FLOAT(4))),2)[AVG_MARK]
	FROM GROUPS,FACULTY,PROGRESS
		WHERE FACULTY.FACULTY like 'рнб'
	GROUP BY ROLLUP (PROGRESS.SUBJECT,GROUPS.PROFESSION) 
	ORDER BY AVG_MARK DESC
--#2
	SELECT PROGRESS.SUBJECT,GROUPS.PROFESSION,
	ROUND(AVG(CAST(PROGRESS.NOTE AS FLOAT(4))),2)[AVG_MARK]
	FROM GROUPS,FACULTY,PROGRESS
		WHERE FACULTY.FACULTY like 'рнб'
	GROUP BY CUBE (PROGRESS.SUBJECT,GROUPS.PROFESSION) 
	ORDER BY AVG_MARK DESC
--#3
	SELECT PROGRESS.SUBJECT,GROUPS.PROFESSION,
	ROUND(AVG(CAST(PROGRESS.NOTE AS FLOAT(4))),2)[AVG_MARK]
	FROM GROUPS,FACULTY,PROGRESS
		WHERE FACULTY.FACULTY like 'рнб'
	GROUP BY PROGRESS.SUBJECT,GROUPS.PROFESSION
				UNION
	SELECT PROGRESS.SUBJECT,GROUPS.PROFESSION,
	ROUND(AVG(CAST(PROGRESS.NOTE AS FLOAT(4))),2)[AVG_MARK]
	FROM GROUPS,FACULTY,PROGRESS
		WHERE FACULTY.FACULTY like 'урхр'
	GROUP BY PROGRESS.SUBJECT,GROUPS.PROFESSION
--#4
	SELECT PROGRESS.SUBJECT,GROUPS.PROFESSION,
	ROUND(AVG(CAST(PROGRESS.NOTE AS FLOAT(4))),2)[AVG_MARK]
	FROM GROUPS,FACULTY,PROGRESS
		WHERE FACULTY.FACULTY like 'рнб'
	GROUP BY PROGRESS.SUBJECT,GROUPS.PROFESSION
				UNION ALL
	SELECT PROGRESS.SUBJECT,GROUPS.PROFESSION,
	ROUND(AVG(CAST(PROGRESS.NOTE AS FLOAT(4))),2)[AVG_MARK]
	FROM GROUPS,FACULTY,PROGRESS
		WHERE FACULTY.FACULTY like 'урхр'
	GROUP BY PROGRESS.SUBJECT,GROUPS.PROFESSION
--#5
	SELECT PROGRESS.SUBJECT,GROUPS.PROFESSION,
	ROUND(AVG(CAST(PROGRESS.NOTE AS FLOAT(4))),2)[AVG_MARK]
	FROM GROUPS,FACULTY,PROGRESS
		WHERE FACULTY.FACULTY like 'рнб'
	GROUP BY PROGRESS.SUBJECT,GROUPS.PROFESSION
				INTERSECT
	SELECT PROGRESS.SUBJECT,GROUPS.PROFESSION,
	ROUND(AVG(CAST(PROGRESS.NOTE AS FLOAT(4))),2)[AVG_MARK]
	FROM GROUPS,FACULTY,PROGRESS
		WHERE FACULTY.FACULTY like 'урхр'
	GROUP BY PROGRESS.SUBJECT,GROUPS.PROFESSION

--#6
	SELECT PROGRESS.SUBJECT,GROUPS.PROFESSION,
	ROUND(AVG(CAST(PROGRESS.NOTE AS FLOAT(4))),2)[AVG_MARK]
	FROM GROUPS,FACULTY,PROGRESS
		WHERE FACULTY.FACULTY like 'рнб'
	GROUP BY PROGRESS.SUBJECT,GROUPS.PROFESSION
				EXCEPT
	SELECT PROGRESS.SUBJECT,GROUPS.PROFESSION,
	ROUND(AVG(CAST(PROGRESS.NOTE AS FLOAT(4))),2)[AVG_MARK]
	FROM GROUPS,FACULTY,PROGRESS
		WHERE FACULTY.FACULTY like 'урхр'
	GROUP BY PROGRESS.SUBJECT,GROUPS.PROFESSION

	