--lab11.2
--#1
	DECLARE @NAME NVARCHAR(50),@NAMES NVARCHAR(MAX) ='';
	DECLARE NAMECURSOR CURSOR 
		FOR SELECT НАЗВАНИЕ_ОБОРУДОВАНИЯ FROM Оборудование
	OPEN NAMECURSOR
	FETCH NAMECURSOR INTO @NAME;
	WHILE @@FETCH_STATUS=0
	BEGIN
	SET @NAMES = RTRIM(@NAME)+','+@NAMES;
	FETCH NAMECURSOR INTO @NAME;
	END
	CLOSE NAMECURSOR
	GO
--#2
--DEALLOCATE NAMECURSOR
	--#2.1
		DECLARE @NAME NVARCHAR(50),@NAMES NVARCHAR(MAX) ='';
		DECLARE NAMECURSOR CURSOR LOCAL
			FOR SELECT НАЗВАНИЕ_ОБОРУДОВАНИЯ FROM Оборудование
		OPEN NAMECURSOR
		FETCH NAMECURSOR INTO @NAME;
		PRINT '1. '+  @NAME;
		GO
		DECLARE @NAME NVARCHAR(50);
		FETCH NAMECURSOR INTO @NAME;
		PRINT '2. '+  @NAME;
		GO
	--#2.2
		DECLARE @NAME NVARCHAR(50),@NAMES NVARCHAR(MAX) ='';
		DECLARE NAMECURSOR CURSOR GLOBAL
			FOR SELECT НАЗВАНИЕ_ОБОРУДОВАНИЯ FROM Оборудование
		OPEN NAMECURSOR
		FETCH NAMECURSOR INTO @NAME;
		PRINT '1. '+  @NAME;
		GO
		DECLARE @NAME NVARCHAR(50);
		FETCH NAMECURSOR INTO @NAME;
		PRINT '2. '+  @NAME;
		CLOSE NAMECURSOR
		GO
--#3
	--#3.1
		CREATE TABLE #TEMP
		(
			NAME NVARCHAR(60),
			CAUSE NVARCHAR(90)
		)
		INSERT INTO #TEMP SELECT Название_Оборудования,Причина_Списания FROM Списанное_оборудование
		SELECT * FROM #TEMP
		DECLARE @NAME NVARCHAR(60),@CAUSE NVARCHAR(90);
		DECLARE STATCURSOR CURSOR LOCAL STATIC
			FOR SELECT NAME,CAUSE FROM #TEMP
		OPEN STATCURSOR
		UPDATE #TEMP SET CAUSE = 'Устарел' WHERE NAME LIKE 'samsung'
		DELETE #TEMP WHERE NAME LIKE 'WTR 2'
		FETCH STATCURSOR INTO @NAME, @CAUSE
		WHILE @@FETCH_STATUS=0
		BEGIN
			PRINT @NAME + ' ' + @CAUSE;
			FETCH STATCURSOR INTO @NAME , @CAUSE;
		END
		CLOSE STATCURSOR
		DROP TABLE #TEMP
		GO
	--#3.2
		CREATE TABLE #TEMP
		(
			NAME NVARCHAR(60),
			CAUSE NVARCHAR(90)
		)
		INSERT INTO #TEMP SELECT Название_Оборудования,Причина_Списания FROM Списанное_оборудование
		SELECT * FROM #TEMP
		DECLARE @NAME NVARCHAR(60),@CAUSE NVARCHAR(90);
		DECLARE STATCURSOR CURSOR LOCAL DYNAMIC
			FOR SELECT NAME,CAUSE FROM #TEMP
		OPEN STATCURSOR
		UPDATE #TEMP SET CAUSE = 'Устарел' WHERE NAME LIKE 'samsung'
		DELETE #TEMP WHERE NAME LIKE 'WTR 2'
		FETCH STATCURSOR INTO @NAME, @CAUSE
		WHILE @@FETCH_STATUS=0
		BEGIN
			PRINT @NAME + ' ' + @CAUSE;
			FETCH STATCURSOR INTO @NAME , @CAUSE;
		END
		CLOSE STATCURSOR
		DROP TABLE #TEMP
		GO
	--#4
	DECLARE @NAME CHAR(10),@SURNAME VARCHAR(50),@ID INT
	DECLARE FACKCURSOR CURSOR LOCAL DYNAMIC SCROLL 
		FOR SELECT ROW_NUMBER()OVER (ORDER BY Имя_Ответсвенного)[COL_NUM],
			Имя_Ответсвенного,Фамилия_Ответственного
			FROM Ответственный
	OPEN FACKCURSOR
		FETCH FIRST FROM FACKCURSOR INTO @ID,@NAME,@SURNAME
		PRINT 'ПЕРВАЯ СТРОКА :'+CAST(@ID AS NVARCHAR(30))+@NAME + @SURNAME
		FETCH NEXT FROM FACKCURSOR INTO @ID,@NAME,@SURNAME
		PRINT 'СЛЕДУЮЩАЯ СТРОКА :'+CAST(@ID AS NVARCHAR(30))+@NAME + @SURNAME
		FETCH LAST FROM FACKCURSOR INTO @ID,@NAME,@SURNAME
		PRINT 'ПОСЛЕДНЯЯ СТРОКА :'+CAST(@ID AS NVARCHAR(30))+@NAME + @SURNAME
		FETCH PRIOR FROM FACKCURSOR INTO @ID,@NAME,@SURNAME
		PRINT 'ПРЕДЫДУЩАЯ СТРОКА ОТ ТЕКУЩЕЙ :'+CAST(@ID AS NVARCHAR(30))+@NAME + @SURNAME
		FETCH RELATIVE-1 FROM FACKCURSOR INTO @ID,@NAME,@SURNAME
		PRINT '3-Я С КОНЦА :'+CAST(@ID AS NVARCHAR(30))+@NAME + @SURNAME
		FETCH RELATIVE 3 FROM FACKCURSOR INTO @ID,@NAME,@SURNAME
		PRINT 'ПОСЛЕДНЯЯ СТРОКА :'+CAST(@ID AS NVARCHAR(30))+@NAME + @SURNAME
		FETCH ABSOLUTE 2 FROM FACKCURSOR INTO @ID,@NAME,@SURNAME
		PRINT 'ПЯТАЯ С НАЧАЛА СТРОКА :'+CAST(@ID AS NVARCHAR(30))+@NAME + @SURNAME
		FETCH ABSOLUTE -1 FROM FACKCURSOR INTO @ID,@NAME,@SURNAME
		PRINT 'ЧЕТВЕРТАЯ С КОНЦА СТРОКА :'+CAST(@ID AS NVARCHAR(30))+@NAME + @SURNAME
	CLOSE FACKCURSOR
	GO
--#5
	CREATE TABLE #TEMP
	(
		DATE DATE,
		DOLJN NVARCHAR(50)
	)
	INSERT INTO #TEMP SELECT Дата_приема_на_работу,Должность FROM Ответственный
	SELECT *FROM #TEMP;
	DECLARE @DATE DATE,@DOLJN NVARCHAR(50)
	DECLARE CURSS CURSOR LOCAL DYNAMIC 
		FOR SELECT DATE,DOLJN FROM #TEMP
	OPEN CURSS
	FETCH CURSS INTO @DATE,@DOLJN;
	DELETE #TEMP WHERE CURRENT OF CURSS
	FETCH CURSS INTO @DATE,@DOLJN
	UPDATE #TEMP SET DOLJN = 'КОНСУЛЬТАНТ' WHERE CURRENT OF CURSS
	CLOSE CURSS
	SELECT * FROM #TEMP
	GO
--#6
	--#6.1
		DROP TABLE #TEMP
		CREATE TABLE #TEMP 
		(
			ID INT,
			NAME NVARCHAR(60),
			CAUSE NVARCHAR(90),
			DATESP DATE,
	
		)
		INSERT INTO #TEMP SELECT * FROM Списанное_оборудование
	----------
		--DEALLOCATE #CURSS
		SELECT *FROM #TEMP
			DECLARE CURSS CURSOR LOCAL DYNAMIC
				FOR SELECT #TEMP.ID,#TEMP.NAME,#TEMP.CAUSE,#TEMP.DATESP FROM #TEMP
					INNER JOIN Списанное_оборудование
						ON #TEMP.ID = Списанное_оборудование.Id
		DECLARE @ID INT, @NAME NVARCHAR(60),@CAUSE NVARCHAR(90),@DATESP DATE
		OPEN CURSS
			FETCH CURSS INTO @ID,@NAME,@CAUSE,@DATESP
			WHILE @@FETCH_STATUS=0
			BEGIN
				IF(@ID=4)
					DELETE #TEMP WHERE CURRENT OF CURSS
				FETCH CURSS INTO @ID,@NAME,@CAUSE,@DATESP
			END
		CLOSE CURSS
		SELECT *FROM #TEMP
		GO
	--#6.2
		DECLARE CURSS CURSOR LOCAL DYNAMIC
			FOR SELECT Количество,Название_Оборудования FROM Оборудование
				WHERE Оборудование.Название_Оборудования LIKE 'Huawei'
		SELECT Количество,Название_Оборудования FROM Оборудование
				WHERE Оборудование.Название_Оборудования LIKE 'Huawei'
		DECLARE @NUMBER INT, @NAME NVARCHAR(30)
		OPEN CURSS
			FETCH CURSS INTO @NUMBER,@NAME
			UPDATE Оборудование SET Количество = Количество+1 WHERE CURRENT OF CURSS
		CLOSE CURSS
		SELECT Количество,Название_Оборудования FROM Оборудование
				WHERE Оборудование.Название_Оборудования LIKE 'Huawei'
		GO




	