--lab11
--#1
	DECLARE SUBJCURS CURSOR FOR
		SELECT SUBJECT FROM SUBJECT
			INNER JOIN PULPIT 
				ON SUBJECT.PULPIT = PULPIT.PULPIT
			WHERE PULPIT.PULPIT LIKE '%»—Ë“%'

	DECLARE @subject NVARCHAR(10), @subjects NVARCHAR (200)='';
	OPEN SUBJCURS;
	FETCH SUBJCURS INTO @subject;
	PRINT'Í‡ÚÍËÂ Ì‡Á‚‡ÌËˇ ‰ËÒˆËÔÎËÌ ËÁ Ú‡·ÎËˆ˚ SUBJECT ‚ Ó‰ÌÛ ÒÚÓÍÛ ˜ÂÂÁ Á‡ÔˇÚÛ˛';
	while @@FETCH_STATUS=0
	begin
		--PRINT @subject;
		SET @subjects = RTRIM(@subject)+','+@subjects;
		FETCH SUBJCURS INTO @subject;
	end
	PRINT @subjects
	close SUBJCURS
--#2
	--2.1 LOCAL
		DECLARE PROGR CURSOR LOCAL 
			FOR SELECT NOTE,PDATE FROM PROGRESS

		DECLARE @MARK INT ,@DATE DATE;
		OPEN PROGR
		FETCH PROGR INTO @MARK,@DATE;
		PRINT '1.MARK:'+CONVERT(NVARCHAR(20),@MARK)+' DATE:'+CAST(@DATE AS VARCHAR(20));
		GO
		--PROGR Õ≈ —”Ÿ≈—“¬”≈“
		DECLARE @MARK INT ,@DATE DATE;
		FETCH PROGR INTO @MARK,@DATE;
		PRINT '2.MARK:'+CONVERT(NVARCHAR(20),@MARK)+' DATE:'+CAST(@DATE AS VARCHAR(20));
		GO
	--2.2 GLOBAL(DEFAULT)
		DECLARE PROGR CURSOR 
			FOR SELECT NOTE,PDATE FROM PROGRESS

		DECLARE @MARK INT ,@DATE DATE;
		OPEN PROGR
		FETCH PROGR INTO @MARK,@DATE;
		PRINT '1.MARK:'+CONVERT(NVARCHAR(20),@MARK)+' DATE:'+CAST(@DATE AS VARCHAR(20));
		GO
		--PROGR Õ≈ —”Ÿ≈—“¬”≈“
		DECLARE @MARK INT ,@DATE DATE;
		FETCH PROGR INTO @MARK,@DATE;
		PRINT '2.MARK:'+CONVERT(NVARCHAR(20),@MARK)+' DATE:'+CAST(@DATE AS VARCHAR(20));
		GO
		CLOSE PROGR


--#3
	--#3.1
		CREATE TABLE #TEMP
		(
			SUBJECT CHAR(10),
			IDSTUDENT INT,
			PDATE DATE,
			NOTE INT,
		)
		INSERT INTO #TEMP SELECT*FROM PROGRESS
		SELECT *FROM #TEMP
		DECLARE STATICCURS CURSOR LOCAL STATIC
			FOR SELECT * FROM #TEMP
		DECLARE @ID INT, @SUBJ CHAR(10), @PDAT DATE, @MARK INT;
		OPEN STATICCURS
			PRINT ' ŒÀ»◊≈—“¬Œ —“–Œ  :'+CAST(@@CURSOR_ROWS AS VARCHAR(5));
			UPDATE #TEMP SET IDSTUDENT = 10000 WHERE SUBJECT LIKE 'Œ¿Ëœ'
			DELETE #TEMP WHERE PDATE = '2013-12-01'
			SELECT *FROM #TEMP
		FETCH STATICCURS INTO @SUBJ,@ID,@PDAT,@MARK
		WHILE @@FETCH_STATUS=0
		BEGIN
			PRINT @SUBJ +' '+ CONVERT(NVARCHAR(20),@ID) +' '+ CONVERT(NVARCHAR(20),@PDAT) + ' '+ CONVERT(NVARCHAR(20),@MARK) 
			FETCH STATICCURS INTO @SUBJ,@ID,@PDAT,@MARK
		END
		CLOSE STATICCURS
		DROP TABLE #TEMP
		GO
	--#3.2
		CREATE TABLE #TEMP
		(
			SUBJECT CHAR(10),
			IDSTUDENT INT,
			PDATE DATE,
			NOTE INT,
		)
		INSERT INTO #TEMP SELECT*FROM PROGRESS
		SELECT *FROM #TEMP
		DECLARE STATICCURS CURSOR LOCAL DYNAMIC
			FOR SELECT * FROM #TEMP
		DECLARE @ID INT, @SUBJ CHAR(10), @PDAT DATE, @MARK INT;
		OPEN STATICCURS
			PRINT ' ŒÀ»◊≈—“¬Œ —“–Œ  :'+CAST(@@CURSOR_ROWS AS VARCHAR(5));
			UPDATE #TEMP SET IDSTUDENT = 10000 WHERE SUBJECT LIKE 'Œ¿Ëœ'
			DELETE #TEMP WHERE PDATE = '2013-12-01'
			SELECT *FROM #TEMP
		FETCH STATICCURS INTO @SUBJ,@ID,@PDAT,@MARK
		WHILE @@FETCH_STATUS=0
		BEGIN
			PRINT @SUBJ +' '+ CONVERT(NVARCHAR(20),@ID) +' '+ CONVERT(NVARCHAR(20),@PDAT) + ' '+ CONVERT(NVARCHAR(20),@MARK) 
			FETCH STATICCURS INTO @SUBJ,@ID,@PDAT,@MARK
		END
		CLOSE STATICCURS
		DROP TABLE #TEMP
		GO
--#4
	DECLARE @FACK CHAR(10),@FACKNAME VARCHAR(50)
	DECLARE FACKCURSOR CURSOR LOCAL DYNAMIC SCROLL 
		FOR SELECT ROW_NUMBER()OVER (ORDER BY FACULTY)[COL_NUM],
			FACULTY_NAME
			FROM FACULTY
	OPEN FACKCURSOR
	FETCH FIRST FROM FACKCURSOR INTO @FACK,@FACKNAME
	PRINT 'œ≈–¬¿ﬂ —“–Œ ¿ :'+@FACK + @FACKNAME
	FETCH NEXT FROM FACKCURSOR INTO @FACK,@FACKNAME
	PRINT '—À≈ƒ”ﬁŸ¿ﬂ —“–Œ ¿ :'+@FACK + @FACKNAME
	FETCH LAST FROM FACKCURSOR INTO @FACK,@FACKNAME
	PRINT 'œŒ—À≈ƒÕﬂﬂ —“–Œ ¿ :'+@FACK + @FACKNAME
	FETCH PRIOR FROM FACKCURSOR INTO @FACK,@FACKNAME
	PRINT 'œ–≈ƒ€ƒ”Ÿ¿ﬂ —“–Œ ¿ Œ“ “≈ ”Ÿ≈… :'+@FACK + @FACKNAME
	FETCH RELATIVE-2 FROM FACKCURSOR INTO @FACK,@FACKNAME
	PRINT '3-ﬂ —  ŒÕ÷¿ :'+@FACK + @FACKNAME
	FETCH RELATIVE 3 FROM FACKCURSOR INTO @FACK,@FACKNAME
	PRINT 'œŒ—À≈ƒÕﬂﬂ —“–Œ ¿ :'+@FACK + @FACKNAME
	FETCH ABSOLUTE 5 FROM FACKCURSOR INTO @FACK,@FACKNAME
	PRINT 'œﬂ“¿ﬂ — Õ¿◊¿À¿ —“–Œ ¿ :'+@FACK + @FACKNAME
	FETCH ABSOLUTE -4 FROM FACKCURSOR INTO @FACK,@FACKNAME
	PRINT '◊≈“¬≈–“¿ﬂ —  ŒÕ÷¿ —“–Œ ¿ :'+@FACK + @FACKNAME
	GO
--#5
	CREATE TABLE #TEMP
	(
		FACULTY CHAR(10),
		FACULTY_NAME NVARCHAR(50)
	)
	INSERT INTO #TEMP SELECT *FROM FACULTY
	SELECT * FROM #TEMP

	DECLARE FACKCURSOR CURSOR LOCAL DYNAMIC 
		FOR SELECT * FROM #TEMP
	DECLARE @FACK CHAR(10),@FACKNAME NVARCHAR(50)
	OPEN FACKCURSOR 
	FETCH FACKCURSOR INTO @FACK,@FACKNAME
	DELETE #TEMP WHERE CURRENT OF FACKCURSOR;
	FETCH FACKCURSOR INTO @FACK,@FACKNAME
	UPDATE #TEMP SET FACULTY = 'NEW FACK' WHERE CURRENT OF FACKCURSOR
	CLOSE FACKCURSOR
	SELECT * FROM #TEMP
	DROP TABLE #TEMP
	GO
--#6
	--#6.1
		CREATE TABLE #TEMP
			(
				SUBJECT CHAR(10),
				IDSTUDENT INT,
				PDATE DATE,
				NOTE INT,
			)
		INSERT INTO #TEMP SELECT*FROM PROGRESS
		SELECT * FROM #TEMP
		DECLARE DELSTUDCURS CURSOR LOCAL DYNAMIC
			FOR SELECT #TEMP.SUBJECT,#TEMP.IDSTUDENT,#TEMP.PDATE,#TEMP.NOTE FROM #TEMP
				INNER JOIN STUDENT
					ON #TEMP.IDSTUDENT=STUDENT.IDSTUDENT
				INNER JOIN GROUPS
					ON STUDENT.IDGROUP=GROUPS.IDGROUP
		DECLARE @SUBJ CHAR(10),@ID INT,@PDAT DATE, @MARK INT
		OPEN DELSTUDCURS
			FETCH DELSTUDCURS INTO @SUBJ,@ID,@PDAT,@MARK
			PRINT @SUBJ +' '+ CONVERT(NVARCHAR(20),@ID) +' '+ CONVERT(NVARCHAR(20),@PDAT) + ' '+ CONVERT(NVARCHAR(20),@MARK) 
			WHILE @@FETCH_STATUS=0
				BEGIN
					IF(@MARK<=4)
						DELETE #TEMP WHERE CURRENT OF DELSTUDCURS
					FETCH DELSTUDCURS INTO @SUBJ,@ID,@PDAT,@MARK
					PRINT @SUBJ +' '+ CONVERT(NVARCHAR(20),@ID) +' '+ CONVERT(NVARCHAR(20),@PDAT) + ' '+ CONVERT(NVARCHAR(20),@MARK) 
				END
		SELECT * FROM #TEMP
		CLOSE DELSTUDCURS
		DROP TABLE #TEMP
		GO
	--#6.2
		SELECT * FROM PROGRESS
		DECLARE NOTECURSOR CURSOR LOCAL DYNAMIC
			FOR SELECT * FROM PROGRESS
				WHERE PROGRESS.IDSTUDENT = 1001
		DECLARE @SUBJ CHAR(10),@ID INT, @PDAT DATE, @MARK INT;
		OPEN NOTECURSOR
		FETCH NOTECURSOR INTO @SUBJ,@ID,@PDAT,@MARK
		PRINT @SUBJ +' '+ CONVERT(NVARCHAR(20),@ID) +' '+ CONVERT(NVARCHAR(20),@PDAT) + ' '+ CONVERT(NVARCHAR(20),@MARK) 
		UPDATE PROGRESS SET NOTE = NOTE+1 WHERE CURRENT OF NOTECURSOR;
		SELECT*FROM PROGRESS
		CLOSE NOTECURSOR
		GO