--Lab12B
	--#4
		--B--
			BEGIN TRANSACTION
			SELECT @@SPID
			INSERT STUDENT VALUES(2,'ASD SXXC XCX','1994-02-10',NULL,NULL);
			UPDATE AUDITORIUM_TYPE SET AUDITORIUM_TYPE = 'ка-я'
														WHERE AUDITORIUM_TYPE LIKE '%ка-K%'
		--T1--
		--T2--
		ROLLBACK;
		--INSERT INTO AUDITORIUM_TYPE VALUES('TEMP','QWE');
		UPDATE AUDITORIUM_TYPE SET AUDITORIUM_TYPE = 'TEMP' WHERE AUDITORIUM_TYPENAME = 'QWE'
	--#5
		--B--
		BEGIN TRAN
		--T1--
		UPDATE AUDITORIUM_TYPE SET AUDITORIUM_TYPE = 'LC'
														WHERE AUDITORIUM_TYPE LIKE '%TEMP%'
		COMMIT;
		--T2--
	--#6
		DELETE AUDITORIUM_TYPE WHERE AUDITORIUM_TYPE LIKE 'TEMPS'
		--B--
		BEGIN TRAN
		--T1--
		INSERT INTO AUDITORIUM_TYPE VALUES('TEMPS','TEMP DESCRIPTION');
		COMMIT;
		--T2--
	--#7
		--B--
		BEGIN TRAN
		DELETE AUDITORIUM_TYPE WHERE AUDITORIUM_TYPE LIKE'%TEMPS%';
		INSERT INTO AUDITORIUM_TYPE VALUES('TEMPS','TEMP DESCRIPTION');
		UPDATE AUDITORIUM_TYPE SET AUDITORIUM_TYPENAME = 'NOT TEMP DESCRIPTION' WHERE AUDITORIUM_TYPE LIKE '%TEMPS%'
		SELECT * FROM AUDITORIUM_TYPE WHERE AUDITORIUM_TYPE LIKE 'TEMPS';
		--T1--
		COMMIT;
		SELECT * FROM AUDITORIUM_TYPE WHERE AUDITORIUM_TYPE LIKE 'TEMPS';
		--T2--

