--Lab12A
	--#1
		GO
			SET NOCOUNT ON
			IF EXISTS(SELECT*FROM SYS.OBJECTS
									WHERE	OBJECT_ID = object_id(N'DBO.TEMP'))
				DROP TABLE TEMP;
			DECLARE @C INT, @FLAG CHAR ='C';
			SET IMPLICIT_TRANSACTIONS ON
			CREATE TABLE TEMP
			(
				ID INT,
				NAME NVARCHAR(30),
				SURNAME NVARCHAR(30)
			)
			INSERT INTO TEMP VALUES
			(0,'KIRILL','DRACH'),
			(1,'VADIM','YATCKEVICH'),
			(2,'DIMA','LESHUK')
			SET @C = (SELECT COUNT(*) FROM TEMP)
			PRINT 'NUMBER OF STUDENTS: '+CAST(@C AS NVARCHAR(10));
			IF(@FLAG LIKE 'C')
				COMMIT;
			ELSE
				ROLLBACK;
			SET IMPLICIT_TRANSACTIONS OFF;
			IF EXISTS(SELECT*FROM SYS.OBJECTS
									WHERE	OBJECT_ID = object_id(N'DBO.TEMP'))
				PRINT 'TABLE TEMP EXISTS'
			ELSE
				PRINT 'TABLE TEMP DOESNT EXIST';
	--#2
		GO
			BEGIN TRY
				BEGIN TRAN
					DELETE STUDENT WHERE IDSTUDENT = 1001;
					INSERT INTO STUDENT 
						VALUES(200,'ASD SXXC XCX','1994-02-10',NULL,NULL)
					UPDATE STUDENT SET IDGROUP = 200
						WHERE IDSTUDENT = 1000
				COMMIT TRAN;
			END TRY
			BEGIN CATCH
				PRINT 'ОШИБКА:'+CASE
													WHEN ERROR_NUMBER()=547 AND PATINDEX('%INSERT%',ERROR_MESSAGE())>0
														THEN 'Конфликт инструкции INSERT с ограничением FOREIGN KEY "STUDENT_GROUP_FK".'
													WHEN ERROR_NUMBER()=547 AND PATINDEX('%UPDATE%',ERROR_MESSAGE())>0
														THEN 'Конфликт инструкции UPDATE с ограничением FOREIGN KEY "STUDENT_GROUP_FK".'
													ELSE
														'Другая ошибка: '+ cast(ERROR_NUMBER() AS VARCHAR(5))+ERROR_MESSAGE()
												END;
				IF @@TRANCOUNT>0
				ROLLBACK TRAN;
			END CATCH
	--#3
		GO
			DECLARE @POINT NVARCHAR(20);
			BEGIN TRY
				BEGIN TRAN
					DELETE AUDITORIUM_TYPE WHERE AUDITORIUM_TYPE LIKE '%ЛБ-X%'
					SET @POINT = 'P1';
					SAVE TRAN @POINT;
					INSERT INTO AUDITORIUM_TYPE VALUES('ЛБ-X','Химическая лаборатория');
					SET @POINT = 'P2';
					SAVE TRAN @POINT;
					UPDATE STUDENT SET IDGROUP = 200
						WHERE IDSTUDENT = 1000
				COMMIT TRAN;
			END TRY
			BEGIN CATCH
			PRINT 'ОШИБКА:'+CASE
													WHEN ERROR_NUMBER()=547 AND PATINDEX('%UPDATE%',ERROR_MESSAGE())>0
														THEN 'Конфликт инструкции UPDATE с ограничением FOREIGN KEY "STUDENT_GROUP_FK".'
													ELSE
														'Другая ошибка: '+ cast(ERROR_NUMBER() AS VARCHAR(5))+ERROR_MESSAGE()
												END;
				IF @@TRANCOUNT>0
				BEGIN
					PRINT 'CHECK POINT: '+@POINT;
					ROLLBACK TRAN @POINT;
					COMMIT TRAN;
				END
			END CATCH
	--#4
		--A--
			GO
				SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
				BEGIN TRAN
		--T1--
				SELECT @@SPID, 'insert Student' 'результат', * FROM STUDENT 
																										WHERE NAME LIKE 'ASD SXXC XCX'
				SELECT @@SPID, 'UPDATE AUDITORIUM_TYPE' 'результат', * FROM AUDITORIUM_TYPE 
																										WHERE AUDITORIUM_TYPE LIKE '%ЛБ-С%'
				COMMIT;
		--T2--
	--#5
		--A--
		SET TRANSACTION ISOLATION LEVEL READ COMMITTED
		BEGIN TRAN
		SELECT COUNT(*) FROM AUDITORIUM_TYPE WHERE AUDITORIUM_TYPE LIKE '%LC%';
		--T1--
		--T2--
		SELECT 'UPDATE AUDITORIUM_TYPE' 'результат', COUNT(*) FROM AUDITORIUM_TYPE 
																										WHERE AUDITORIUM_TYPE LIKE '%LC%';
		COMMIT;

	--#6
		SET TRANSACTION ISOLATION LEVEL REPEATABLE READ
		BEGIN TRAN
		SELECT * FROM AUDITORIUM_TYPE WHERE AUDITORIUM_TYPE = '%TEMPS%'
		--T1--
		--T2--
		SELECT CASE
							WHEN AUDITORIUM_TYPE = 'TEMPS' 
								THEN 'INSERTED ROW INTO AUDITORIUM_TYPE'
							ELSE
								''
							END 'REZULT',AUDITORIUM_TYPENAME FROM AUDITORIUM_TYPE WHERE AUDITORIUM_TYPE LIKE 'TEMPS'
		COMMIT;
	--#7
		--A--
		SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
		BEGIN TRAN
		DELETE AUDITORIUM_TYPE WHERE AUDITORIUM_TYPE LIKE'%TEMPS%';
		INSERT INTO AUDITORIUM_TYPE VALUES('TEMPS','TEMP DESCRIPTION');
		UPDATE AUDITORIUM_TYPE SET AUDITORIUM_TYPENAME = 'NOT TEMP DESCRIPTION' WHERE AUDITORIUM_TYPE LIKE '%TEMPS%'
		SELECT * FROM AUDITORIUM_TYPE WHERE AUDITORIUM_TYPE LIKE 'TEMPS';
		--T1--
		SELECT * FROM AUDITORIUM_TYPE WHERE AUDITORIUM_TYPE LIKE 'TEMPS';
		--T2--
		COMMIT;
	--#8
		BEGIN TRAN
		INSERT AUDITORIUM_TYPE VALUES('TASK8','DESCRIPTION FOR TASK8')
		BEGIN TRAN
			UPDATE AUDITORIUM_TYPE SET AUDITORIUM_TYPENAME='DESCRIPTION'
															WHERE AUDITORIUM_TYPE LIKE 'TASK8'
			COMMIT;
			IF @@TRANCOUNT>0
				ROLLBACK;
		SELECT * FROM AUDITORIUM_TYPE
