--lab14
	--#1
		GO
			CREATE FUNCTION COUNT_STUDENTS(@FACULTY VARCHAR(20) = NULL)
			RETURNS INT AS 
			BEGIN
				DECLARE @RC INT =0;
				SET @RC =(SELECT COUNT(*) FROM STUDENT
										INNER JOIN GROUPS
											ON STUDENT.IDGROUP = GROUPS.IDGROUP
												INNER JOIN FACULTY
													ON GROUPS.FACULTY = FACULTY.FACULTY
														WHERE FACULTY.FACULTY = @FACULTY)
				RETURN @RC;
			END
		GO
			DECLARE @COUNT INT = dbo.COUNT_STUDENTS('ÒÎÂ');
			PRINT 'ÊÎËÈ×ÅÑÒÂÎ ÑÒÓÄÅÍÒÎÂ: ' + CAST(@COUNT AS VARCHAR(10));
		GO
			ALTER FUNCTION COUNT_STUDENTS(@FACULTY VARCHAR(20) = NULL,@PROF VARCHAR(20)=NULL)
				RETURNS INT
					AS
					BEGIN
						DECLARE @RC INT =0;
						SET @RC =(SELECT COUNT(*) FROM STUDENT
										INNER JOIN GROUPS
											ON STUDENT.IDGROUP = GROUPS.IDGROUP
												INNER JOIN FACULTY
													ON GROUPS.FACULTY = FACULTY.FACULTY
														WHERE FACULTY.FACULTY = @FACULTY
																		AND
																	GROUPS.PROFESSION = @PROF)
						RETURN @RC;
					END
		GO
		SELECT PROFESSION,FACULTY.FACULTY,dbo.COUNT_STUDENTS(FACULTY.FACULTY,PROFESSION)[ÊÎËÈ×ÅÑÒÂÎ ÑÒÓÄÅÍÒÎÂ ÍÀ ÔÀÊÓËÜÒÅÒÀÕ] FROM STUDENT
			INNER JOIN GROUPS
				ON STUDENT.IDGROUP = GROUPS.IDGROUP
					INNER JOIN FACULTY
						ON GROUPS.FACULTY = FACULTY.FACULTY
			GROUP BY FACULTY.FACULTY , PROFESSION
		
		DROP FUNCTION DBO.COUNT_STUDENTS
		--#2
		GO
			CREATE FUNCTION FSUBJECTS(@PULPIT VARCHAR(20) = NULL)
				RETURNS VARCHAR(300)
					AS
					BEGIN
						DECLARE @TEMP VARCHAR(40);
						DECLARE @RET_VALUE VARCHAR(300)='';
						DECLARE CURS CURSOR LOCAL DYNAMIC
							FOR SELECT FACULTY FROM PULPIT
								WHERE PULPIT.PULPIT = @PULPIT;
						OPEN CURS;
							FETCH CURS INTO @TEMP
							WHILE @@FETCH_STATUS=0
								BEGIN
									SET @RET_VALUE =RTRIM(@TEMP)+', '+@RET_VALUE;
									FETCH CURS INTO @TEMP;
								END
						CLOSE CURS;
						RETURN @RET_VALUE;
					END
			GO
				SELECT PULPIT,DBO.FSUBJECTS(PULPIT)[ÄÈÑÖÈÏËÈÍÛ] FROM PULPIT
			--DROP FUNCTION DBO.FSUBJECTS
		--#3
			GO
				CREATE FUNCTION FFACPUL(@PULPIT CHAR(20)=NULL,@FACULTY CHAR(10)=NULL)
					RETURNS TABLE
					AS 
						RETURN
							SELECT PULPIT,FACULTY.FACULTY FROM PULPIT 
								LEFT OUTER JOIN FACULTY
									ON PULPIT.FACULTY = FACULTY.FACULTY
										WHERE PULPIT.PULPIT = ISNULL(@PULPIT,PULPIT.PULPIT)
														AND
													FACULTY.FACULTY = ISNULL(@FACULTY,FACULTY.FACULTY);
			GO
				SELECT *FROM DBO.FFACPUL(NULL,NULL);
				SELECT *FROM DBO.FFACPUL('ÒèÏ',NULL);
				SELECT *FROM DBO.FFACPUL(NULL,'ËÕÔ');
				SELECT *FROM DBO.FFACPUL('ÒÍÂèÎÕÒ','ÕÒèÒ');
		--#4
			GO
				CREATE FUNCTION FCTEACHER(@PULPIT CHAR(20)=NULL)
					RETURNS INT
					AS
					BEGIN
						DECLARE @COUNT INT = 0;
						SET @COUNT = (SELECT COUNT(*) FROM TEACHER
														WHERE TEACHER.PULPIT = ISNULL(@PULPIT,TEACHER.PULPIT))
						RETURN @COUNT;
					END
			GO
				SELECT PULPIT,DBO.FCTEACHER(PULPIT)[ÊÎËÈ×ÅÑÒÂÎ ÏÐÅÏÎÄÀÂÀÒÅËÅÉ] FROM PULPIT
				SELECT DBO.FCTEACHER(NULL)[ÊÎËÈ×ÅÑÒÂÎ ÏÐÅÏÎÄÀÂÀÒÅËÅÉ]
			DROP FUNCTION DBO.FCTEACHER 
		--#6
			GO 
				CREATE FUNCTION PULPIT_NUMBER(@PULPIT VARCHAR(30))
					RETURNS INT
					AS
					BEGIN
						DECLARE @RC INT = 0;
						SET @RC = (select count(PULPIT) from PULPIT where FACULTY = @PULPIT);
						RETURN @RC;
					END
			GO 
				CREATE FUNCTION GROUP_NUMBER(@FACULTY VARCHAR(30))
					RETURNS INT
					AS
					BEGIN
						DECLARE @RC INT = 0;
						SET @RC = (select count(IDGROUP) from GROUPS where FACULTY = @FACULTY);
						RETURN @RC;
					END
			GO 
				CREATE FUNCTION PROFESSION_NUMBER(@FACULTY VARCHAR(30))
					RETURNS INT
					AS
					BEGIN
						DECLARE @RC INT = 0;
						SET @RC = (select count(PROFESSION) from PROFESSION where FACULTY = @FACULTY);
						RETURN @RC;
					END



			GO
				CREATE FUNCTION FACULTY_REPORT(@C INT) RETURNS @FR TABLE
				(
					FACULTY VARCHAR(50),
					PULPIT_NUMBER INT,
					GROUP_NUMBER INT,
					STUDENT_NUMBER INT,
					PROFESSION_NUMBER INT
				)
				AS
					BEGIN
						DECLARE CC CURSOR LOCAL STATIC FOR
							SELECT FACULTY FROM FACULTY
								WHERE DBO.COUNT_STUDENTS(FACULTY)>@C;
						DECLARE @F VARCHAR(30);
						OPEN CC;
						FETCH CC INTO @F;
						WHILE @@FETCH_STATUS=0
						BEGIN
							INSERT @FR VALUES(  @F,
							DBO.PULPIT_NUMBER(@F),
							DBO.GROUP_NUMBER(@F),
							dbo.COUNT_STUDENTS(@F),
	            DBO.PROFESSION_NUMBER(@F)  );
							FETCH CC INTO @F;
						END
					RETURN;
					END
				GO
					SELECT * FROM dbo.FACULTY_REPORT(4)
				DROP FUNCTION DBO.FACULTY_REPORT
